"""add title to path_mappings

Revision ID: b7ecadbea177
Revises: a4f70c944b8c
Create Date: 2026-07-18 02:14:13.318540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ecadbea177'
down_revision: Union[str, None] = 'a4f70c944b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('path_mappings', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('path_mappings', 'title')
    # ### end Alembic commands ###
