"""add write-outcome audit actions and previous-value snapshots

Revision ID: 45d78a971872
Revises: 60d721d925e4
Create Date: 2026-07-18 07:46:37.927808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45d78a971872'
down_revision: Union[str, None] = '60d721d925e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('previous_content', sa.Text(), nullable=True))
    op.add_column('audit_log', sa.Column('previous_name', sa.String(length=255), nullable=True))
    op.alter_column('audit_log', 'action',
               existing_type=mysql.ENUM('APPROVED', 'REJECTED', 'EDITED', 'REGENERATED'),
               type_=sa.Enum('APPROVED', 'REJECTED', 'EDITED', 'REGENERATED', 'WRITE_SUCCEEDED', 'WRITE_FAILED', name='auditaction'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'action',
               existing_type=sa.Enum('APPROVED', 'REJECTED', 'EDITED', 'REGENERATED', 'WRITE_SUCCEEDED', 'WRITE_FAILED', name='auditaction'),
               type_=mysql.ENUM('APPROVED', 'REJECTED', 'EDITED', 'REGENERATED'),
               existing_nullable=False)
    op.drop_column('audit_log', 'previous_name')
    op.drop_column('audit_log', 'previous_content')
    # ### end Alembic commands ###
