"""add commit_sha to approval_records

Revision ID: 60d721d925e4
Revises: fd640799cfc2
Create Date: 2026-07-18 04:05:43.269597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d721d925e4'
down_revision: Union[str, None] = 'fd640799cfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_records', sa.Column('commit_sha', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_records', 'commit_sha')
    # ### end Alembic commands ###
