"""add is_promotable signal to path_mappings

Revision ID: 7235ac9fffe1
Revises: 45d78a971872
Create Date: 2026-07-18 08:41:42.459501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7235ac9fffe1'
down_revision: Union[str, None] = '45d78a971872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this backfills existing rows to False instead of
    # failing on the NOT NULL constraint (unlike the initial schema, this
    # table already has rows by the time this migration runs).
    op.add_column(
        'path_mappings',
        sa.Column('is_promotable', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('path_mappings', 'is_promotable')
    # ### end Alembic commands ###
