"""initial schema

Revision ID: a4f70c944b8c
Revises: 
Create Date: 2026-07-18 00:50:21.237753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f70c944b8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('GITHUB_APP', 'PUBLIC_SNAPSHOT', name='reposourcetype'), nullable=False),
    sa.Column('github_installation_id', sa.String(length=64), nullable=True),
    sa.Column('last_synced_sha', sa.String(length=64), nullable=True),
    sa.Column('root_page_id', sa.String(length=64), nullable=True),
    sa.Column('structural_approver', sa.String(length=255), nullable=True),
    sa.Column('content_approver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('batch_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'DONE', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('parent_mapping_id', sa.Integer(), nullable=True),
    sa.Column('section_anchor', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('last_synced_sha', sa.String(length=64), nullable=True),
    sa.Column('is_promoted', sa.Boolean(), nullable=False),
    sa.Column('name_origin', sa.Enum('LLM_PROPOSED', 'HUMAN_EDITED', name='nameorigin'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_mapping_id'], ['path_mappings.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'path', name='uq_repo_path')
    )
    op.create_table('approval_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_mapping_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('CREATE', 'PROMOTE', 'RENAME', 'DELETE', 'CONTENT_EDIT', name='changetype'), nullable=False),
    sa.Column('proposed_content', sa.Text(), nullable=True),
    sa.Column('current_content', sa.Text(), nullable=True),
    sa.Column('proposed_name', sa.String(length=255), nullable=True),
    sa.Column('proposed_location', sa.String(length=1024), nullable=True),
    sa.Column('pr_context', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('approver', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['path_mapping_id'], ['path_mappings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('APPROVED', 'REJECTED', 'EDITED', 'REGENERATED', name='auditaction'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('pr_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_record_id'], ['approval_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    op.drop_table('approval_records')
    op.drop_table('path_mappings')
    op.drop_table('jobs')
    op.drop_table('repos')
    # ### end Alembic commands ###
