"""add diff_patch to approval_records

Revision ID: fd640799cfc2
Revises: b7ecadbea177
Create Date: 2026-07-18 04:04:20.801069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd640799cfc2'
down_revision: Union[str, None] = 'b7ecadbea177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_records', sa.Column('diff_patch', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_records', 'diff_patch')
    # ### end Alembic commands ###
